# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, unique=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, db_index=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
